name: Publish package to npm

on:
  push:
    branches: ["main"]

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Node 20
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'
      - name: Install dependencies
        run: npm ci
        working-directory: ./react-circle-wave
      - name: Build
        run: npm run build
        working-directory: ./react-circle-wave
      - name: Copy README
        run: cp ./README.md ./react-circle-wave
      - run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
