name: Publish package to npm

on:
  push:
    branches: ["main"]

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Node 20
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'
      - name: Change direcotry to package path
        run: cd react-circle-wave
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: Copy README
        run: cp ../README.md ./
