name: Deploy static content to Pages

on:
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # Single deploy job since we're just deploying
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Node 20
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - name: Install website dependencies
        run: npm ci
        working-directory: ./website
      - name: Build website
        run: npm run build
        working-directory: ./website

      - name: Install demo-music-player dependencies
        run: npm ci
        working-directory: ./demo-music-player
      - name: Build demo-music-player
        run: npm run build
        working-directory: ./demo-music-player
      - name: Copy demo-music-player to website
        run: cp -R ./demo-music-player/build ./website/build/demo-music-player

      - name: Install react-circle-wave dependencies
        run: npm ci
        working-directory: ./react-circle-wave
      - name: Build storybook static
        run: npm run buildbuild-storybook
        working-directory: ./react-circle-wave
      - name: Copy storybook to website
        run: cp -R ./react-circle-wave/storybook-static ./website/build/storybook-static

      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'website/build'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
